#pragma once
#ifndef GLOBALS_H
#define GLOBALS_H

#define ENABLE_DEBUG 1
#define ENABLE_WIREFRAME 0

#define ENABLE_FACE_MESH 0
#define ENABLE_DEBUG_POINTS 0

#define RESIZED_IMAGE_WIDTH 460		// Try different numbers (460)
#define RESIZED_IMAGE_HEIGHT 613	// Try different numbers

#define FACE_MESH_TOPHEAD_INDEX 441
#define FACE_MESH_BOTHEAD_INDEX 22
#define FACE_MESH_RIGHTCONTOUR_INDEX 358
#define FACE_MESH_LEFTCONTOUR_INDEX 775

#endif